print ('Welcome to git')
print ('Tomorrow is cloudy')
print ('Board 0: Burton: never used before probablly never will')
print ('Board 1: SportCheck Board: first board')
print ('Board 2: Lib Tech: skate banana')
print ('Board 3: Nitro: prime')
print ('Board 4: Rome: mod rocker')
print ('Board 5: Salomon: huck knife')
print ('Board 6: DC: maybe next board? or go back to rome?')
print ('Board 7: November: cat board?')
